@tool
extends EditorPlugin

const LoggingConfig = preload("res://addons/deep_thought/utils/logger/logging_config.gd")

func _enter_tree():
	# Инициализируем логирование
	LoggingConfig.setup_logging()
	
	# Добавляем типы ресурсов
	add_custom_type("GenerationContext", "Resource", preload("res://addons/deep_thought/core/generator/generation_context.gd"), preload("res://icon.svg"))
	add_custom_type("MapBuffer", "Resource", preload("res://addons/deep_thought/core/generator/map_buffer.gd"), preload("res://icon.svg"))
	add_custom_type("BlockLibrary", "Resource", preload("res://addons/deep_thought/core/blocks/block_library.gd"), preload("res://icon.svg"))
	add_custom_type("BlockType", "Resource", preload("res://addons/deep_thought/core/blocks/block_type.gd"), preload("res://icon.svg"))
	add_custom_type("GeneratorPreset", "Resource", preload("res://addons/deep_thought/core/generator/generator_preset.gd"), preload("res://icon.svg"))
	add_custom_type("NoiseGenerator", "Resource", preload("res://addons/deep_thought/core/generator/noise_generator.gd"), preload("res://icon.svg"))
	add_custom_type("ChunkGenerationModule", "Resource", preload("res://addons/deep_thought/core/generator/chunk_generation_module.gd"), preload("res://icon.svg"))
	add_custom_type("BasicTerrainGenerator", "Resource", preload("res://addons/deep_thought/core/generator/modules/basic_terrain_generator.gd"), preload("res://icon.svg"))
	add_custom_type("AdvancedTerrainGenerator", "Resource", preload("res://addons/deep_thought/core/generator/modules/advanced_terrain_generator.gd"), preload("res://icon.svg"))
	add_custom_type("TestTerrainGenerator", "Resource", preload("res://addons/deep_thought/core/generator/modules/test_terrain_generator.gd"), preload("res://icon.svg"))
	add_custom_type("Chunk", "Node3D", preload("res://addons/deep_thought/core/world/chunk.gd"), preload("res://icon.svg"))
	add_custom_type("ChunkRenderer", "Node3D", preload("res://addons/deep_thought/core/world/chunk_renderer.gd"), preload("res://icon.svg"))
	add_custom_type("WorldBase", "Node3D", preload("res://addons/deep_thought/core/world/world_base.gd"), preload("res://icon.svg"))
	add_custom_type("WorldPreview", "Node3D", preload("res://addons/deep_thought/previewers/world_preview.gd"), preload("res://icon.svg"))
	add_custom_type("OverlayManager", "Node", preload("res://addons/deep_thought/core/overlay/overlay_manager.gd"), preload("res://icon.svg"))
	add_custom_type("OverlayGenerator", "Resource", preload("res://addons/deep_thought/core/overlay/overlay_generator.gd"), preload("res://icon.svg"))
	add_custom_type("OverlayBrush", "Resource", preload("res://addons/deep_thought/core/overlay/overlay_brush.gd"), preload("res://icon.svg"))
	add_custom_type("OverlayChunkData", "Resource", preload("res://addons/deep_thought/core/overlay/overlay_chunk_data.gd"), preload("res://icon.svg"))
	add_custom_type("BlockOverlayState", "Resource", preload("res://addons/deep_thought/core/blocks/block_overlay_state.gd"), preload("res://icon.svg"))
	add_custom_type("BlockOverlay", "Resource", preload("res://addons/deep_thought/core/blocks/block_overlay.gd"), preload("res://icon.svg"))
	add_custom_type("Biome", "Resource", preload("res://addons/deep_thought/core/world/biomes/biome.gd"), preload("res://icon.svg"))
	add_custom_type("BiomeGenerator", "Resource", preload("res://addons/deep_thought/core/world/biomes/biome_generator.gd"), preload("res://icon.svg"))
	add_custom_type("DefaultBiomeGenerator", "Resource", preload("res://addons/deep_thought/core/world/biomes/default_biome_generator.gd"), preload("res://icon.svg"))
	add_custom_type("Planet", "Node3D", preload("res://addons/deep_thought/core/world/planet/planet.gd"), preload("res://icon.svg"))
	add_custom_type("PlanetConfig", "Resource", preload("res://addons/deep_thought/core/world/planet/planet_config.gd"), preload("res://icon.svg"))
	add_custom_type("GoldbergSphere", "Node3D", preload("res://addons/deep_thought/core/world/planet/goldberg_sphere.gd"), preload("res://icon.svg"))
	add_custom_type("Pawn", "Node3D", preload("res://addons/deep_thought/core/pawns/pawn.gd"), preload("res://icon.svg"))
	add_custom_type("PawnConfig", "Resource", preload("res://addons/deep_thought/core/pawns/pawn_config.gd"), preload("res://icon.svg"))
	add_custom_type("StatBlock", "Resource", preload("res://addons/deep_thought/core/pawns/stats/stat_block.gd"), preload("res://icon.svg"))
	add_custom_type("StatModifier", "Resource", preload("res://addons/deep_thought/core/pawns/stats/stat_modifier.gd"), preload("res://icon.svg"))
	add_custom_type("BodyStructure", "Resource", preload("res://addons/deep_thought/core/pawns/parts/body_structure.gd"), preload("res://icon.svg"))
	add_custom_type("BodyPart", "Resource", preload("res://addons/deep_thought/core/pawns/parts/body_part.gd"), preload("res://icon.svg"))
	add_custom_type("Prosthesis", "Resource", preload("res://addons/deep_thought/core/pawns/parts/prosthesis.gd"), preload("res://icon.svg"))
	add_custom_type("PawnVisual", "Node3D", preload("res://addons/deep_thought/core/pawns/visual/pawn_visual.gd"), preload("res://icon.svg"))
	
	# Новые типы скелета
	add_custom_type("PawnSkeleton", "Node3D", preload("res://addons/deep_thought/core/pawns/skeleton/pawn_skeleton.gd"), preload("res://icon.svg"))
	add_custom_type("PawnSkeletonData", "Resource", preload("res://addons/deep_thought/core/pawns/skeleton/pawn_skeleton_data.gd"), preload("res://icon.svg"))
	add_custom_type("AttachmentData", "Resource", preload("res://addons/deep_thought/core/pawns/skeleton/attachment_data.gd"), preload("res://icon.svg"))
	add_custom_type("UnifiedBoneData", "Resource", preload("res://addons/deep_thought/core/pawns/skeleton/unified_bone_data.gd"), preload("res://icon.svg"))
	
	add_custom_type("ChunkEditor", "Node", preload("res://addons/deep_thought/editor/chunk_editor.gd"), preload("res://icon.svg"))
	add_custom_type("FlyCamera", "Camera3D", preload("res://addons/deep_thought/utils/fly_camera.gd"), preload("res://icon.svg"))

func _exit_tree():
	# Удаляем типы ресурсов
	remove_custom_type("GenerationContext")
	remove_custom_type("MapBuffer")
	remove_custom_type("BlockLibrary")
	remove_custom_type("BlockType")
	remove_custom_type("GeneratorPreset")
	remove_custom_type("NoiseGenerator")
	remove_custom_type("ChunkGenerationModule")
	remove_custom_type("BasicTerrainGenerator")
	remove_custom_type("AdvancedTerrainGenerator")
	remove_custom_type("TestTerrainGenerator")
	remove_custom_type("Chunk")
	remove_custom_type("ChunkRenderer")
	remove_custom_type("WorldBase")
	remove_custom_type("WorldPreview")
	remove_custom_type("OverlayManager")
	remove_custom_type("OverlayGenerator")
	remove_custom_type("OverlayBrush")
	remove_custom_type("OverlayChunkData")
	remove_custom_type("BlockOverlayState")
	remove_custom_type("BlockOverlay")
	remove_custom_type("Biome")
	remove_custom_type("BiomeGenerator")
	remove_custom_type("DefaultBiomeGenerator")
	remove_custom_type("Planet")
	remove_custom_type("PlanetConfig")
	remove_custom_type("GoldbergSphere")
	remove_custom_type("Pawn")
	remove_custom_type("PawnConfig")
	remove_custom_type("StatBlock")
	remove_custom_type("StatModifier")
	remove_custom_type("BodyStructure")
	remove_custom_type("BodyPart")
	remove_custom_type("Prosthesis")
	remove_custom_type("PawnVisual")
	
	# Удаляем новые типы скелета
	remove_custom_type("PawnSkeleton")
	remove_custom_type("PawnSkeletonData")
	remove_custom_type("AttachmentData")
	remove_custom_type("ArmSkeletonController")
	remove_custom_type("LegSkeletonController")
	remove_custom_type("UnifiedBoneData")
	remove_custom_type("AutoSkeletonController")
	
	remove_custom_type("ChunkEditor")
	remove_custom_type("FlyCamera")
