name: Compatibility Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  compatibility:
    name: Test Godot Compatibility
    runs-on: ubuntu-latest
    strategy:
      matrix:
        godot-version: [4.3, 4.4, 4.5]
        
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Godot ${{ matrix.godot-version }}
      uses: godotengine/setup-godot@v1
      with:
        godot-version: ${{ matrix.godot-version }}
        
    - name: Test compatibility
      run: |
        echo "Testing compatibility with Godot ${{ matrix.godot-version }}"
        
        # Create minimal test project
        mkdir -p test_project
        cd test_project
        
        # Create project.godot
        echo "config_version=5" > project.godot
        echo "" >> project.godot
        echo "[application]" >> project.godot
        echo "config/name=\"Compatibility Test\"" >> project.godot
        echo "run/main_scene=\"\"" >> project.godot
        echo "config/features=PackedStringArray(\"4.4\", \"GL Compatibility\")" >> project.godot
        echo "config/icon=\"res://icon.svg\"" >> project.godot
        echo "" >> project.godot
        echo "[rendering]" >> project.godot
        echo "renderer/rendering_method=\"gl_compatibility\"" >> project.godot
        
        # Copy addon
        cp -r ../addons test_project/
        
        # Test if project loads
        godot --headless --check-only || exit 1
        echo "✅ Compatible with Godot ${{ matrix.godot-version }}"
        
    - name: Report compatibility
      run: |
        echo "🎉 Addon is compatible with Godot ${{ matrix.godot-version }}" 